server:
  port: 8080

spring:
  application:
    name: DeepImage
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/deepimage
    username: postgres
    password: postgres

mybatis-plus:
  mapper-locations: classpath:/mappers/**/*.xml
  global-config:
    db-config:
      logic-delete-field: delete_flag
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

sa-token:
  jwt-secret-key: deepImage-secret-key
  timeout: 1800
  token-name: Authorization
  is-log: true
  is-concurrent: true
  is-share: false
  token-style: jwt
  is-write-header: true
  token-prefix: Bearer

deepimage:
  auth:
    refresh-ttl-seconds: 2592000   # 30天